### PR TITLE
add custom changes to ros2-beta

### PR DESCRIPTION
**Pull request by saraalarab1**
custom changes to branch having ros diagnostics

### CODE REVIEW

**Comment by saraalarab1** [comment]
branch tested with realsense camera, custom changes are functional and diagnostics works as well

**Comment by jplapp** [comment]
you set the `diagnostics_period` value, right? :see_no_evil:

**Comment by saraalarab1** [comment]
> you set the `diagnostics_period` value, right? see_no_evil

haha yess. I figured it might be because the default value was 0, so when I set it it worked :D

**Review by jplapp — APPROVED** [review]
good then

**Pull request merged**
